// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barista_messages.proto

public final class BaristaMessages {
  private BaristaMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ApplicationSettingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ApplicationSettings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string last_project_directory = 1;</code>
     *
     * <pre>
     * The last project directory which was loaded
     * </pre>
     */
    boolean hasLastProjectDirectory();
    /**
     * <code>optional string last_project_directory = 1;</code>
     *
     * <pre>
     * The last project directory which was loaded
     * </pre>
     */
    java.lang.String getLastProjectDirectory();
    /**
     * <code>optional string last_project_directory = 1;</code>
     *
     * <pre>
     * The last project directory which was loaded
     * </pre>
     */
    com.google.protobuf.ByteString
        getLastProjectDirectoryBytes();
  }
  /**
   * Protobuf type {@code ApplicationSettings}
   */
  public static final class ApplicationSettings extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ApplicationSettings)
      ApplicationSettingsOrBuilder {
    // Use ApplicationSettings.newBuilder() to construct.
    private ApplicationSettings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ApplicationSettings(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ApplicationSettings defaultInstance;
    public static ApplicationSettings getDefaultInstance() {
      return defaultInstance;
    }

    public ApplicationSettings getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ApplicationSettings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              lastProjectDirectory_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaristaMessages.internal_static_ApplicationSettings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaristaMessages.internal_static_ApplicationSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaristaMessages.ApplicationSettings.class, BaristaMessages.ApplicationSettings.Builder.class);
    }

    public static com.google.protobuf.Parser<ApplicationSettings> PARSER =
        new com.google.protobuf.AbstractParser<ApplicationSettings>() {
      public ApplicationSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApplicationSettings(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ApplicationSettings> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LAST_PROJECT_DIRECTORY_FIELD_NUMBER = 1;
    private java.lang.Object lastProjectDirectory_;
    /**
     * <code>optional string last_project_directory = 1;</code>
     *
     * <pre>
     * The last project directory which was loaded
     * </pre>
     */
    public boolean hasLastProjectDirectory() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string last_project_directory = 1;</code>
     *
     * <pre>
     * The last project directory which was loaded
     * </pre>
     */
    public java.lang.String getLastProjectDirectory() {
      java.lang.Object ref = lastProjectDirectory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastProjectDirectory_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string last_project_directory = 1;</code>
     *
     * <pre>
     * The last project directory which was loaded
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLastProjectDirectoryBytes() {
      java.lang.Object ref = lastProjectDirectory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastProjectDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      lastProjectDirectory_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLastProjectDirectoryBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLastProjectDirectoryBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static BaristaMessages.ApplicationSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaristaMessages.ApplicationSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaristaMessages.ApplicationSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaristaMessages.ApplicationSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaristaMessages.ApplicationSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaristaMessages.ApplicationSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BaristaMessages.ApplicationSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BaristaMessages.ApplicationSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BaristaMessages.ApplicationSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaristaMessages.ApplicationSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BaristaMessages.ApplicationSettings prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ApplicationSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ApplicationSettings)
        BaristaMessages.ApplicationSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaristaMessages.internal_static_ApplicationSettings_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaristaMessages.internal_static_ApplicationSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaristaMessages.ApplicationSettings.class, BaristaMessages.ApplicationSettings.Builder.class);
      }

      // Construct using BaristaMessages.ApplicationSettings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lastProjectDirectory_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaristaMessages.internal_static_ApplicationSettings_descriptor;
      }

      public BaristaMessages.ApplicationSettings getDefaultInstanceForType() {
        return BaristaMessages.ApplicationSettings.getDefaultInstance();
      }

      public BaristaMessages.ApplicationSettings build() {
        BaristaMessages.ApplicationSettings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BaristaMessages.ApplicationSettings buildPartial() {
        BaristaMessages.ApplicationSettings result = new BaristaMessages.ApplicationSettings(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lastProjectDirectory_ = lastProjectDirectory_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaristaMessages.ApplicationSettings) {
          return mergeFrom((BaristaMessages.ApplicationSettings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaristaMessages.ApplicationSettings other) {
        if (other == BaristaMessages.ApplicationSettings.getDefaultInstance()) return this;
        if (other.hasLastProjectDirectory()) {
          bitField0_ |= 0x00000001;
          lastProjectDirectory_ = other.lastProjectDirectory_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaristaMessages.ApplicationSettings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaristaMessages.ApplicationSettings) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object lastProjectDirectory_ = "";
      /**
       * <code>optional string last_project_directory = 1;</code>
       *
       * <pre>
       * The last project directory which was loaded
       * </pre>
       */
      public boolean hasLastProjectDirectory() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string last_project_directory = 1;</code>
       *
       * <pre>
       * The last project directory which was loaded
       * </pre>
       */
      public java.lang.String getLastProjectDirectory() {
        java.lang.Object ref = lastProjectDirectory_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastProjectDirectory_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string last_project_directory = 1;</code>
       *
       * <pre>
       * The last project directory which was loaded
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLastProjectDirectoryBytes() {
        java.lang.Object ref = lastProjectDirectory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastProjectDirectory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string last_project_directory = 1;</code>
       *
       * <pre>
       * The last project directory which was loaded
       * </pre>
       */
      public Builder setLastProjectDirectory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        lastProjectDirectory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_project_directory = 1;</code>
       *
       * <pre>
       * The last project directory which was loaded
       * </pre>
       */
      public Builder clearLastProjectDirectory() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lastProjectDirectory_ = getDefaultInstance().getLastProjectDirectory();
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_project_directory = 1;</code>
       *
       * <pre>
       * The last project directory which was loaded
       * </pre>
       */
      public Builder setLastProjectDirectoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        lastProjectDirectory_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ApplicationSettings)
    }

    static {
      defaultInstance = new ApplicationSettings(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ApplicationSettings)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplicationSettings_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ApplicationSettings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026barista_messages.proto\"5\n\023ApplicationS" +
      "ettings\022\036\n\026last_project_directory\030\001 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ApplicationSettings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApplicationSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ApplicationSettings_descriptor,
        new java.lang.String[] { "LastProjectDirectory", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
